##
# docker-compose.yml
#
# This is the default docker-compose file to bring up/down containers.
# note: docker-osx-dev alse keys off of this file to determine file sync paths
##
mysql:
  image: mysql:5.6
  volumes:
    - ../../../../../volumes/var/lib/mysql:/var/lib/mysql
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=admin
magento2:
  build: m2docker
  volumes:
    - ../../../../../volumes/var/www/magento2:/var/www/magento2
  ports:
    - "80:80"
  links:
    - mysql
  environment: 
    - MYSQL_USER=root
    - MYSQL_PASSWORD=admin
    - PUBLIC_HOST=docker.localhost.com
  command: bash -c "/usr/local/bin/runserver.sh" 

